name: SelfServer NodeJS Webpack

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.2'
    - run: npm install
    - run: npm run build

    - name: Upload dist directory
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: dist
        
    - name: Checkout the repository again to update dist folder
      uses: actions/checkout@v4
      with:
        ref: test 
        path: . 

    - name: Copy dist folder to the repository
      run: |
        #cp -r dist/* ./dist
        git config --local user.email "787449591@qq.com" 
        git config --local user.name "kobayashi7777" 
        git add -f ./dist
        git commit -m "Update dist folder in the repository"
        git push origin test 
